# Generated by Django 5.2 on 2025-09-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipehistory',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipehistory',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
