# Generated by Django 5.2 on 2025-10-20 15:04
from django.db import migrations
from django.db.models import Count


def remove_duplicates(apps, schema_editor):
    RecipeHistory = apps.get_model("input", "RecipeHistory")

    # Find duplicates
    duplicates = (
        RecipeHistory.objects.values("user", "url")
        .annotate(url_count=Count("id"))
        .filter(url_count__gt=1)
    )

    # Remove duplicates, keep newest
    for dup in duplicates:
        recipes = RecipeHistory.objects.filter(
            user_id=dup["user"], url=dup["url"]
        ).order_by("-date_time")

        # Delete all except the first (newest)
        for recipe in recipes[1:]:
            recipe.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("input", "0002_recipehistory_instructions_and_more"),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicates, migrations.RunPython.noop
        )  # irreversable data migratoin
    ]
