# Generated by Django 5.2 on 2025-10-23 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_remove_duplicates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipehistory',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterUniqueTogether(
            name='recipehistory',
            unique_together={('user', 'url')},
        ),
    ]
